version: '3.1'

networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gingersnap_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer
    restart: always
    networks:
      - mynetwork
    ports:
      # Expose on 8090 so Quarkus Dev can run on 8080
      - 8090:8080

  cache-manager:
    depends_on:
      db:
        condition: service_healthy
    image: quay.io/gingersnap/cache-manager-mysql:latest
    ports:
      - 11222
      - 8081:8081
    volumes:
      - ./cache-manager-application.properties:/work/config/application.properties
    container_name: cache-manager
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8081/q/health/ready" ]
      timeout: 2s
      retries: 10

  db-syncer:
    depends_on:
      cache-manager:
        condition: service_healthy
    image: quay.io/gingersnap/db-syncer:latest
    ports:
      - 8083
    volumes:
      - ./db-sync-application.properties:/deployments/config/application.properties
    container_name: db-syncer
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8083/q/health/ready" ]
      timeout: 2s
      retries: 10
