apiVersion: v1
kind: Secret
metadata:
  name: db-credential-secret
stringData:
  type: "mysql"
  host: "mysql.demo.svc.cluster.local"
  port: "3306"
  database: "airports"
  username: "gingersnap_user"
  password: "password"
---
apiVersion: gingersnap-project.io/v1alpha1
kind: Cache
metadata:
  name: cache
spec:
  dataSource:
    dbType: MYSQL_8
    secretRef:
      name: db-credential-secret
  deployment:
    type: CLUSTER
    replicas: 1
---
apiVersion: gingersnap-project.io/v1alpha1
kind: EagerCacheRule
metadata:
  name: us-flight
spec:
  cacheRef:
    name: cache
    namespace: demo
  tableName: airports.Flight
  key:
    keyColumns:
      - code
  query:
    enabled: true
---
apiVersion: gingersnap-project.io/v1alpha1
kind: EagerCacheRule
metadata:
  name: us-airport
spec:
  cacheRef:
    name: cache
    namespace: demo
  tableName: airports.Airport
  key:
    keyColumns:
      - id
  query:
    enabled: true
---
apiVersion: gingersnap-project.io/v1alpha1
kind: EagerCacheRule
metadata:
  name: us-aircraft
spec:
  cacheRef:
    name: cache
    namespace: demo
  tableName: airports.Aircraft
  key:
    keyColumns:
      - id
  query:
    enabled: true
---
apiVersion: gingersnap-project.io/v1alpha1
kind: EagerCacheRule
metadata:
  name: us-airline
spec:
  cacheRef:
    name: cache
    namespace: demo
  tableName: airports.Airline
  key:
    keyColumns:
      - id
  query:
    enabled: true
---
apiVersion: gingersnap-project.io/v1alpha1
kind: EagerCacheRule
metadata:
  name: country
spec:
  cacheRef:
    name: cache
    namespace: demo
  tableName: airports.Country
  key:
    keyColumns:
      - id
  query:
    enabled: true
