apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: server
          image: mysql:latest
          # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
          # (this is just an example, not intended to be a production configuration)
          args:
            - --default-authentication-plugin=mysql_native_password
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: gingersnap_user
            - name: MYSQL_PASSWORD
              value: password
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "mysql --host=localhost --user=root --password=$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
          volumeMounts:
            - name: initdb
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true
      volumes:
        - name: initdb
          configMap:
            name: sql-setup
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-setup
data:
  setup.sql: |
    create schema airports;
    GRANT ALL PRIVILEGES ON *.* TO 'gingersnap_user';
    create table airports.Aircraft (
                              id bigint not null,
                              iataMain varchar(255),
                              iataSub varchar(255),
                              longDescription varchar(255),
                              shortDescription varchar(255),
                              primary key (id)
    );

    create table airports.Airline (
                             id bigint not null,
                             iata varchar(255),
                             icao varchar(255),
                             nvls varchar(255),
                             publicName varchar(255),
                             primary key (id)
    );

    create table airports.Airport (
                             id bigint not null,
                             city varchar(255),
                             elevation_ft double precision not null,
                             iata varchar(255),
                             latitude_deg double precision not null,
                             longitude_deg double precision not null,
                             name varchar(255),
                             country_id bigint,
                             primary key (id)
    );

    create table airports.Country (
                             id bigint not null,
                             continent varchar(255),
                             isoCode varchar(255),
                             name varchar(255),
                             primary key (id)
    );

    create table airports.Flight (
                            id bigint not null,
                            code varchar(255),
                            dayOfWeek integer not null,
                            departure boolean,
                            name varchar(255),
                            scheduleTime varchar(255),
                            state varchar(255),
                            terminal integer not null,
                            aircraft_id bigint,
                            airline_id bigint,
                            destination_id bigint,
                            primary key (id)
    );

    create table airports.hibernate_sequence (
        next_val bigint
    );

    insert into airports.hibernate_sequence values ( 1 );

    alter table airports.Airport
        add constraint FKj04qjklwe8vkj8sfsehbcmjr2
            foreign key (country_id)
                references airports.Country (id);

    alter table airports.Flight
        add constraint FK9r3jdupj6x0bqgb5fnk7dr5cn
            foreign key (aircraft_id)
                references airports.Aircraft (id);

    alter table airports.Flight
        add constraint FKiovu1yeejovoyfdigekqm2poq
            foreign key (airline_id)
                references airports.Airline (id);

    alter table airports.Flight
        add constraint FK5dis6my7uigtlf3yplj9a8tf2
            foreign key (destination_id)
                references airports.Airport (id);
